#!/bin/bash



SRC="/home/user/mydata"
DEST="/home/user/backup"


mkdir -p "$DEST"

cp -r "$SRC" "$DEST"


if [ $? -eq 0 ]; then
    echo "✅ Backup created at $DEST on $(date)"
    ls -lrth "$DEST"
else
    echo "❌ Backup failed!"44
    exit 1
fi
